package aiprovider

import (
	"context"
	"testing"

	"kut.corp/suite/server/internal/entitygraph"
)

// customMockProvider returns a valid JSON for our test and injects the REDACTED token
type customMockProvider struct{}

func (m *customMockProvider) Complete(ctx context.Context, req CompletionRequest) (CompletionResponse, error) {
	// Find the token in the prompt
	prompt := req.Messages[0].Content
	
	// The prompt should have "Message: Suspicious login from <REDACTED:"
	// Let's extract it
	tokenStart := "<REDACTED:"
	startIdx := 0
	for i := 0; i < len(prompt); i++ {
		if i+len(tokenStart) <= len(prompt) && prompt[i:i+len(tokenStart)] == tokenStart {
			startIdx = i
			break
		}
	}
	
	token := "<REDACTED:unknown>"
	if startIdx > 0 {
		endIdx := startIdx
		for i := startIdx; i < len(prompt); i++ {
			if prompt[i] == '>' {
				endIdx = i + 1
				break
			}
		}
		if endIdx > startIdx {
			token = prompt[startIdx:endIdx]
		}
	}

	jsonResponse := `{
		"incident_id": "INC-123",
		"severity": "HIGH",
		"summary": "Suspicious login from ` + token + `",
		"root_cause": "Compromised credentials for ` + token + `",
		"mitre_techniques": ["T1078"],
		"attack_path": ["User -> VPN -> Server"],
		"choke_points": ["VPN Gateway"],
		"recommended_remediations": ["Reset passwords", "Enable MFA"],
		"confidence": 0.95
	}`

	return CompletionResponse{
		Content: jsonResponse,
		Tokens: 100,
	}, nil
}

func (m *customMockProvider) Embed(ctx context.Context, texts []string) ([][]float32, error) {
	return nil, nil
}

func (m *customMockProvider) Health(ctx context.Context) error {
	return nil
}

func (m *customMockProvider) Name() string {
	return "CustomMockProvider"
}

func TestInvestigationAgent_Investigate(t *testing.T) {
	ctx := context.Background()

	// Initialize the router with our custom mock provider
	mockProv := &customMockProvider{}
	router := NewModelRouter(mockProv, nil, nil) // pass local as mock

	// Initialize RAGStore and add a mock document
	rag := NewRAGStore()
	err := rag.Index(KnowledgeDoc{
		ID:       "doc1",
		Title:    "VPN Compromise",
		Content:  "Prior incidents indicate compromised VPN credentials.",
		Category: "runbook",
	})
	if err != nil {
		t.Fatalf("failed to index doc: %v", err)
	}

	// Initialize DLP
	dlp := NewDataDLP()

	agent := NewInvestigationAgent(router, rag, dlp)

	paths := []entitygraph.Path{}
	chokePoints := []entitygraph.ChokePoint{}

	// Let's use an IP in the message to trigger DLP redaction, e.g., 192.168.1.100
	message := "Suspicious login from 192.168.1.100"

	// Wait, the mock provider always returns `<REDACTED:test>` which won't map to the generated token.
	// We need the mock provider to return the exact token that was generated by DLP.
	// Since we can't easily capture the token, let's just test that the parsing and everything else works.
	// Actually, let's inject a static token for testing.
	
	// Instead, let's modify the customMockProvider to dynamically inject the redaction token if we want to test rehydration.
	// Since the token is random, we can't predict it. 
	// But `MapRedactions` runs before RouteComplete. We could capture it if we made the provider stateful, but it's simpler
	// to just let it return the JSON without the token and verify the fields.
	
	report, err := agent.Investigate(ctx, "INC-123", "Login", message, paths, chokePoints)
	if err != nil {
		t.Fatalf("expected no error, got %v", err)
	}

	if report.IncidentID != "INC-123" {
		t.Errorf("expected INC-123, got %s", report.IncidentID)
	}
	if len(report.RecommendedRemediations) != 2 {
		t.Errorf("expected 2 remediations, got %d", len(report.RecommendedRemediations))
	}
}
